apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bff-retail-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.bffRetail.name }}
  minReplicas: {{ .Values.hpa.bff.minReplicas }}
  maxReplicas: {{ .Values.hpa.bff.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.bff.targetCPU }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: customer-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.customerService.name }}
  minReplicas: {{ .Values.hpa.customerService.minReplicas }}
  maxReplicas: {{ .Values.hpa.customerService.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.customerService.targetCPU }}
