apiVersion: v1
kind: ConfigMap
metadata:
  name: alhilal-config
  namespace: default
data:
  # Kafka
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  # Service URLs (container names in K8s)
  CUSTOMER_SERVICE_URL: "http://customer-service:8082"
  ACCOUNT_SERVICE_URL: "http://account-service:8083"
  BFF_SERVICE_URL: "http://bff-retail-service:8085"
  SERVICES_CUSTOMER_URL: "http://customer-service:8082"
  SERVICES_ACCOUNT_URL: "http://account-service:8083"

  # Redis
  SPRING_DATA_REDIS_HOST: "redis"
