apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: alhilal/customer-service:1.0
          imagePullPolicy: Never    # use local image
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: alhilal-config    # load all ConfigMap values
            - secretRef:
                name: alhilal-secrets   # load all Secret values
          # Health checks
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - port: 8082
      targetPort: 8082
